import VersoManual
import Manual.Meta
import Leancourse.Misc.Defs
import Mathlib

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open MyDef

set_option pp.rawOnError true

#doc (Manual) "The natural numbers and reduction rules" =>
%%%
htmlSplit := .never
tag := "nat"
%%%

Before we start with more specific course content, we start by introducing the natural numbers, `ℕ` (which is notation for the type `Nat`), in order to get things rolling and have a running example. Everything else in this part -- types, terms, proofs -- should be easier to read once you have seen how a single type is built and how Lean *computes* with it.

# The natural numbers
%%%
tag := "nat-intro"
%%%

`Nat` is an *inductive* type: it is generated by a fixed list of *constructors* (the different possibilities to _construct_ a natural number), the basic ways to build a value. `Nat` has exactly two (read `a : b` as _`a` is a term of type `b`_, and _`a → b` as the type of maps from `a` to `b`_, and `succ` means the successor of a natural number):

```
Nat.zero : Nat
Nat.succ : Nat → Nat
```

so every natural number is a finite tower of them: `Nat.zero` is `0`, `Nat.succ Nat.zero` is `1`, `Nat.succ (Nat.succ Nat.zero)` is `2`, and so on. (The numerals `0`, `1`, `2` are just notation for these terms.) The general `inductive` declaration -- how you build your *own* types this way -- is the subject of {ref "inductive"}[a later section]; here we only need `Nat` itself.

Paired with the constructors, and generated automatically alongside the type, is one further tool: the *recursor* `Nat.rec`. Where the constructors *build* a value, the recursor *consumes* one -- it is the primitive way to define a function with domain `Nat`. To define some `f : Nat → C` (where `C` is some type), you supply exactly two things: a base value `base : C` for the `zero` case (i.e. `f 0 := base`, where `f 0` is the Lean way to write `f(0)`), and a `step : Nat → C → C` such that, for `succ n` (which equals `n + 1`), you may reuse both `n` and the result already computed for `n`, i.e. you define in this way `f (n + 1) := step n (f n)`. (Note the important notation here: We write `α → β → γ` -- with implicit brackets `g : α → (β → γ)` for a function `g` mapping every `a : α` to a function `β → γ`. So, `g a b : γ`. In other words, this is the Lean and more flexible way to write a function depending on two variables.)

Noting the `example` keyword, as well as the inputs `C, base, step`, we define the terms of type `Nat → C` by introducing a function (using the `fun` keyword, and the mapping rule):

```lean
example (C : Type) (base : C) (step : Nat → C → C) :
    Nat → C :=
  fun n ↦ Nat.rec base step n
```

Pattern matching, and the `cases` and `induction` tactics, which we will encounter in the exercises and below, all compile down to `Nat.rec`. (The recursor has a still more general form, in which the result *type* may itself vary with the `Nat`, and which turns out to unify recursion with the induction principle. That needs the language of *universes*, so we return to it in the {ref "inductive"}[section on inductive types].)

What matters for the next sections is that `Nat.rec` *computes*. Applied to a value that is *literally one of the two constructors*, it selects the matching case -- and the *iota rule* (ι) made precise below is applied (numerals such as `2` are put into constructor form first, so the rule applies to them too):

```
Nat.rec base step Nat.zero      ⟶ base
Nat.rec base step (Nat.succ n)  ⟶ step n (Nat.rec base step n)
```

For a full example, define "double" (note the keyword `def` at the beginning of the line, and the function name `myDouble`, the input `n : Nat` of the function, which returns a `Nat`) through the recursor and watch it reduce on `2` (here, `_` is the name of a variable, which is not used):

```lean
def step (_ j : Nat) : Nat := j + 2

def myDouble (n : Nat) : Nat :=
  Nat.rec 0 step n

--   myDouble 2
-- ⟶ Nat.rec 0 step 2                -- δ: unfold myDouble
-- ⟶ step 1 (Nat.rec 0 step 1)       -- ι on succ, then δβ
-- ⟶ (Nat.rec 0 step 1) + 2          -- δ: unfold step
-- ⟶ (step 0 (Nat.rec 0 step 0)) + 2 -- ι again
-- ⟶ ((Nat.rec 0 step 0) + 2) + 2    -- δ: unfold step
-- ⟶ (0 + 2) + 2  ⟶  4               -- ι on zero, then +
example : myDouble 2 = 4 := rfl
```

The equality `myDouble 2 = 4` needs no proof beyond `rfl` (which is the Lean way of saying that two thing are definitionally equal): both sides *reduce* to a common form. Naming those reduction steps precisely -- and pinning down when two terms are _the same by computation_ -- is what the rest of this chapter is about.

# Definitional equality and `rfl`
%%%
tag := "defeq"
%%%

As we just saw, terms in Lean *reduce*: `myDouble 2` reduces to `4`. A term *reduces*, by a fixed set of steps, toward a simpler form -- `(fun x => x + 1) 4` becomes `5`, and `2 + 2` becomes `4`. Each such step is called a *reduction* and is written `term ⟶ simpler term`. Two terms are *definitionally equal* -- also *judgmentally equal*, written `a ≡ b` -- when they reduce to a common form, and Lean's kernel then treats them as fully *interchangeable*, in particular when it compares types during type-checking. That comparison test is called *conversion* (or *defeq checking*). Definitional equality must be kept apart from *propositional equality* `a = b`, which is itself a `Prop` and may require a genuine proof; the full three-way distinction -- syntactic, definitional, propositional -- is laid out in {ref "equality"}[the appendix on equality].

The tactic `rfl` proves exactly a definitional equality. That is why goals whose two sides are written differently but *reduce* to the same thing close by `rfl`:

```lean
example : 2 + 2 = 4 := rfl
example : Nat.succ 0 = 1 := rfl
```

The `#eval` command (used throughout the {ref "terms"}[chapter on terms]) runs the same reduction and prints the resulting value. So `rfl`, `#eval`, and every "reduces to" below are one and the same phenomenon. The precise steps are the *reduction rules* of the kernel, which we now name in full -- they recur throughout the course whenever a later step is claimed to hold "by definition".

## The reduction rules
%%%
tag := "reduction-rules"
%%%

Definitional equality is not magic -- it is *generated* by a fixed list of reduction rules that the kernel applies to compute terms. Most of the names come from the *lambda calculus* of Alonzo Church in the 1930s, where functions are written `fun x => e` and each rewriting rule carries a Greek letter. Lean's kernel uses six of them:

:::table (align := left) +header
* + Rule
  + Technical name
  + What it does
  + Example
* + α (alpha)
  + α-conversion
  + rename a bound variable
  + `fun x => x` and `fun y => y` agree
* + β (beta)
  + β-reduction
  + apply a function: substitute the argument
  + `(fun x => x + 1) 4 ⟶ 4 + 1`
* + η (eta)
  + η-conversion
  + a function equals its expansion `fun x => f x`
  + `fun x => f x ⟶ f`
* + δ (delta)
  + δ-reduction
  + unfold a definition: replace a constant by its value
  + `twice 3 ⟶ 2 * 3`
* + ι (iota)
  + ι-reduction
  + run a recursor on a constructor
  + `Nat.rec base step (n+1) ⟶ step n (Nat.rec base step n)`
* + ζ (zeta)
  + ζ-reduction
  + substitute a `let`-binding
  + `let x := 4; x + x ⟶ 4 + 4`
:::

*Definitional equality* -- Lean's notion of "the same by computation" -- is *precisely* the equivalence generated by these rules, and that is *precisely* what `rfl` checks: `rfl` proves `a = b` whenever `a` and `b` reduce to a common form. So `rfl` is far stronger than "syntactically identical":

```lean
-- beta, then arithmetic computes (delta + iota)
example : (fun x => x + 1) 4 = 5 := rfl
example : 2 + 2 = 4 := rfl
example : List.length [7, 8, 9] = 3 := rfl

-- eta: a function equals its eta-expansion
example (f : Nat → Nat) : (fun x => f x) = f := rfl

-- zeta: a `let` unfolds
example : (let x := 4; x + x) = 8 := rfl

-- delta + iota: a defined function on a literal
def twice (n : Nat) : Nat := 2 * n
example : twice 3 = 6 := rfl
```

Conversely, `rfl` *fails* when no chain of reductions connects the two sides -- typically when a variable blocks computation. `Nat`'s addition is defined by recursion on its *second* argument, so `n + 0` fires the ι rule and reduces to `n`, whereas `0 + n` is *stuck*: with `n` a bare variable there is no constructor for the recursor to fire on.

```lean
-- `n + 0` reduces to `n`, so this is `rfl`:
example (n : Nat) : n + 0 = n := rfl
```

```lean +error
-- `0 + n` is stuck (nothing to recurse on), so `rfl`
-- fails and you need induction (see below) instead:
example (n : Nat) : 0 + n = n := rfl
```

To actually prove `0 + n = n` you must run the recursor yourself, and for that you need `induction` -- the full `Nat.rec`, which hands you the *induction hypothesis* for the predecessor:

```lean
example (n : Nat) : 0 + n = n := by
  induction n with
  | zero => rfl
  | succ k ih =>
      -- goal: 0 + (k + 1) = k + 1
      -- ι reduces the LHS to succ (0 + k);
      -- `Nat.add_succ` makes that step explicit,
      -- then `ih : 0 + k = k` closes it.
      rw [Nat.add_succ, ih]
```

(Here, `rw [...]` rewrites the goal using an equation; see {ref "rw"}[the `rw` tactic].) Note that `rw [ih]` *alone* fails here: the goal reads `0 + (k + 1) = k + 1`, and the subterm `0 + k` is not yet visible -- it only appears after the ι step `0 + succ k ⟶ succ (0 + k)`, which `Nat.add_succ` performs. This is the same *stuck-until-a-constructor-shows-up* phenomenon one level down.

Recognizing when a goal is "true by reduction" -- and therefore closed by `rfl` -- is one of the most useful instincts to develop; it is exactly the situation later chapters rely on whenever they say a step holds "by definition" or "definitionally".

The ι rule is the one we met concretely with `Nat` in the {ref "nat-intro"}[previous section]: a *recursor* is applied to a value that is literally a *constructor*, selecting the matching case (`Nat.rec base step (Nat.succ n) ⟶ step n (Nat.rec base step n)`). It is the rule that makes every recursive definition reduce -- and its getting *stuck*, when the recursed-on argument is still a variable rather than a constructor, is exactly what blocks `0 + n` above.


::::keepEnv
:::example "Two further rules: proof irrelevance and quotient computation"
Beyond the six lambda-calculus rules, the kernel's definitional equality carries two further rules specific to Lean's foundations:
* *Proof irrelevance*: any two proofs `h₁ h₂ : P` of the same proposition `P : Prop` are definitionally equal. (This is the *`Prop` is special* point, taken up in {ref "prop-vs-type"}[the section on proof irrelevance].)
* *Quotient computation*: the ι-like rule for {ref "quotient-types"}[quotient types], `Quot.lift f h (Quot.mk r a) ⟶ f a`. On `Nat`, a lifted function applied to a `Quot.mk` reduces to the underlying function:

```lean
example (r : Nat → Nat → Prop) (f : Nat → Nat)
    (h : ∀ a b, r a b → f a = f b) (a : Nat) :
    Quot.lift f h (Quot.mk r a) = f a := rfl
```
:::
::::

::::keepEnv
:::example "η for structures"
The η rule also applies to {ref "structures"}[*structures*]: a structure value equals the record of its own projections, `s ≡ ⟨s.1, s.2, …⟩` (η *for structures*). A pair of naturals, for instance, is definitionally its own pair of projections:

```lean
example (p : Nat × Nat) : p = (p.1, p.2) := rfl
```
:::
::::

::::keepEnv
:::example "Reducibility, weak head normal form, and decidability"
How eagerly the δ rule fires is governed by *reducibility* annotations: a `@[reducible]` definition is unfolded freely, an ordinary `def` is unfolded on demand, and an `@[irreducible]` one is left folded. And the kernel usually does not reduce all the way to a *normal form*; it stops at *weak head normal form* (WHNF) -- just far enough to expose the outermost constructor or binder -- which is all that comparing two terms requires. Because this reduction system is *confluent* and *strongly normalizing*, definitional equality is decidable, which is exactly what lets `rfl` and the type-checker terminate.
:::
::::
