import VersoManual
import Manual.Meta
import Leancourse.Misc.Defs
import Mathlib

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open MyDef

set_option pp.rawOnError true

#doc (Manual) "Types" =>
%%%
htmlSplit := .never
tag := "types"
%%%

In all programming languages, you have data types such as `int`, `string` and `float`. In Lean, these exist as well, but you can (and will in this course) define own data types. In all cases, we write `x : α` for a term `x` of type `α`, so we write `False : Bool`, `42 : ℕ`, but also `f : ℕ → ℝ` (for a function from ℕ to ℝ, which is an own type) and `0 ≠ 1 : Prop` (the proposition that 0 and 1 are different natural numbers), which is a proposition. Terms and types can depend on variables, e.g. in `∀ (n : ℕ), n < n + 1 : Prop` (the term `n < n + 1` depends on `n : ℕ`) and `f : (n : ℕ) → (Fin n → ℝ)` where `Fin n` is the type which carries `{0, ..., n-1}` (here, the type `Fin n → ℝ` depends on `n : ℕ`), which is a function `f` with domain `ℕ` such that `f n ∈ ℝ^n`.

Two words for terms recur throughout, depending on their type: a term `h : P` whose type `P` is a `Prop` is called a *proof* (of `P`), while a term `a : α` whose type `α` is a `Type u` is called *data*. So `42 : ℕ` and `true : Bool` are data, whereas any term of the proposition `0 ≠ 1` is a proof of it. (The two kinds of universe, `Prop` and `Type u`, are the subject of the next section.)

As we see, these new data types are more abstract in the sense that Lean understands `ℕ` (and `ℝ`) as infinite types, which are not limited by floating point arithmetic. E.g., `ℕ` actually represents an infinite set that is characterized by containing `0`, and if it contains `n`, then it also contains the successor of `n` (represented by `succ n`). (Frequently, this construction is attributed to Giuseppe Peano.) Accordingly, the real numbers are defined by an equivalence relation on Cauchy sequences, which is quite elaborate.

In Lean, all objects are terms, and every term needs a type. Interestingly, since a type is also some term in the language, it needs a type as well.

# Introduction: the natural numbers
%%%
tag := "types-intro"
%%%

The remark just made about `ℕ` -- every natural number is `0` or a successor -- is not informal hand-waving: it is literally how the type is built, and it is the pattern behind almost every type in Lean. So before anything else we look at `Nat` (Lean's name for `ℕ`) closely enough to reuse it as the running example for the rest of the chapter.

`Nat` is an *inductive* type: it is generated by a fixed list of *constructors*, the basic ways to build a value. `Nat` has exactly two,

```
Nat.zero : Nat
Nat.succ : Nat → Nat
```

so every natural number is a finite tower of them: `Nat.zero` is `0`, `Nat.succ Nat.zero` is `1`, `Nat.succ (Nat.succ Nat.zero)` is `2`, and so on. (The numerals `0`, `1`, `2` are just notation for these terms.) The general `inductive` declaration -- how you build your *own* types this way -- is the subject of {ref "inductive"}[a later section]; here we only need `Nat` itself.

Paired with the constructors, and generated automatically alongside the type, is one further tool: the *recursor* `Nat.rec`. Where the constructors *build* a value, the recursor *consumes* one -- it is the primitive way to define a function *out of* `Nat`. Its type spells out exactly what you must supply:

```lean
#check @Nat.rec
-- {motive : Nat → Sort u} →
--   motive .zero →                     -- zero case
--   ((n : Nat) → motive n →
--      motive n.succ) →                -- succ case
--   (t : Nat) → motive t
```

To define a function on *every* `Nat`, give one case per constructor: a value for `zero`, and for `succ n` a value that may reuse both `n` and the result already computed for `n`. With a data-valued `motive` this is ordinary *recursion*; with a `Prop`-valued one it is the *induction principle* -- one and the same primitive. Pattern matching, and the `cases` and `induction` tactics, all compile down to `Nat.rec`.

What matters for the next section is that `Nat.rec` *computes*. Applied to a value that is *literally one of the two constructors*, it fires and selects the matching case -- this firing is the *iota rule* (ι) made precise below:

```
Nat.rec z s Nat.zero      ⟶ z
Nat.rec z s (Nat.succ n)  ⟶ s n (Nat.rec z s n)
```

For a full example, define "double" through the recursor and watch it reduce on `2`:

```lean
def myDouble (n : Nat) : Nat :=
  Nat.rec (motive := fun _ => Nat) 0 (fun _ ih => ih + 2) n

-- writing s for the step `fun _ ih => ih + 2`, ι fires
-- once per `succ` and returns 0 on `zero`:
--   myDouble 2
--     ⟶ (Nat.rec 0 s 1) + 2        -- ι on outer succ
--     ⟶ ((Nat.rec 0 s 0) + 2) + 2  -- ι again
--     ⟶ (0 + 2) + 2  ⟶  4          -- ι on zero, then +
example : myDouble 2 = 4 := rfl
```

The equality `myDouble 2 = 4` needs no proof beyond `rfl`: both sides *reduce* to a common form. Naming those reduction steps precisely -- and pinning down when two terms are "the same by computation" -- is what the next sections are about.

# Definitional equality and `rfl`
%%%
tag := "defeq"
%%%

One feature runs through everything below, so it is worth naming up front: terms in Lean *compute*. We just watched `myDouble 2` reduce to `4`. A term *reduces*, by a fixed set of steps, toward a simpler form -- `(fun x => x + 1) 4` becomes `5`, and `2 + 2` becomes `4`. Each such step is called a *reduction* and is written `term ⟶ simpler term`. Two terms are *definitionally equal* -- also *judgmentally equal*, written `a ≡ b` -- when they reduce to a common form, and Lean's kernel then treats them as fully *interchangeable*, in particular when it compares types during type-checking. That comparison test is called *conversion* (or *defeq checking*). Definitional equality must be kept apart from *propositional equality* `a = b`, which is itself a `Prop` and may require a genuine proof; the full three-way distinction -- syntactic, definitional, propositional -- is laid out in {ref "equality"}[the appendix on equality].

The tactic `rfl` proves exactly a definitional equality. That is why goals whose two sides are written differently but *compute* to the same thing close by `rfl`:

```lean
example : 2 + 2 = 4 := rfl
example : Sort 1 = Type := rfl
```

The `#eval` command (used throughout the {ref "terms"}[next chapter]) runs the same computation and prints the resulting value. So `rfl`, `#eval`, and every "reduces to" below are one and the same phenomenon. The precise steps are the *reduction rules* of the kernel, which we now name in full -- they recur throughout the course whenever a later step is claimed to hold "by definition".

## The reduction rules
%%%
tag := "reduction-rules"
%%%

Definitional equality is not magic -- it is *generated* by a fixed list of reduction rules that the kernel applies to compute terms. Most of the names come from the *lambda calculus* of Alonzo Church in the 1930s, where functions are written `fun x => e` and each rewriting rule carries a Greek letter. Lean's kernel uses six of them:

:::table (align := left) +header
* + Rule
  + Technical name
  + What it does
  + Example
* + α (alpha)
  + α-conversion
  + rename a bound variable
  + `fun x => x` and `fun y => y` agree
* + β (beta)
  + β-reduction
  + apply a function: substitute the argument
  + `(fun x => x + 1) 4 ⟶ 4 + 1`
* + η (eta)
  + η-conversion
  + a function equals its expansion `fun x => f x`
  + `fun x => f x ⟶ f`
* + δ (delta)
  + δ-reduction
  + unfold a definition: replace a constant by its value
  + `twice 3 ⟶ 2 * 3`
* + ι (iota)
  + ι-reduction
  + run a recursor on a constructor
  + `Nat.rec z s (n+1) ⟶ s n (Nat.rec z s n)`
* + ζ (zeta)
  + ζ-reduction
  + substitute a `let`-binding
  + `let x := 4; x + x ⟶ 4 + 4`
:::

The ι rule is the one we met concretely with `Nat` in the {ref "types-intro"}[introduction]: a *recursor* fires when it is applied to a value that is literally a *constructor*, selecting the matching case (`Nat.rec z s (Nat.succ n) ⟶ s n (Nat.rec z s n)`). It is the rule that makes every recursive definition compute -- and its getting *stuck*, when the recursed-on argument is still a variable rather than a constructor, is exactly what blocks `0 + n` below.

The η rule also applies to *structures*: a structure value equals the record of its own projections, `s ≡ ⟨s.1, s.2, …⟩` (η *for structures*). Beyond the six lambda-calculus rules, the kernel's definitional equality carries two further rules specific to Lean's foundations:

* *Proof irrelevance*: any two proofs `h₁ h₂ : P` of the same proposition `P : Prop` are definitionally equal. (This is the *`Prop` is special* point of the section below.)
* *Quotient computation*: the ι-like rule for {ref "quotient-types"}[quotient types], `Quot.lift f h (Quot.mk r a) ⟶ f a`.

How eagerly the δ rule fires is governed by *reducibility* annotations: a `@[reducible]` definition is unfolded freely, an ordinary `def` is unfolded on demand, and an `@[irreducible]` one is left folded. And the kernel usually does not reduce all the way to a *normal form*; it stops at *weak head normal form* (WHNF) -- just far enough to expose the outermost constructor or binder -- which is all that comparing two terms requires. Because this reduction system is *confluent* and *strongly normalizing*, definitional equality is decidable, which is exactly what lets `rfl` and the type-checker terminate.

*Definitional equality* -- Lean's notion of "the same by computation" -- is *precisely* the equivalence generated by these rules, and that is *precisely* what `rfl` checks: `rfl` proves `a = b` whenever `a` and `b` reduce to a common form. So `rfl` is far stronger than "syntactically identical":

```lean
-- beta, then arithmetic computes (delta + iota)
example : (fun x => x + 1) 4 = 5 := rfl
example : 2 + 2 = 4 := rfl
example : List.length [7, 8, 9] = 3 := rfl

-- eta: a function equals its eta-expansion
example (f : Nat → Nat) : (fun x => f x) = f := rfl

-- zeta: a `let` unfolds
example : (let x := 4; x + x) = 8 := rfl

-- delta + iota: a defined function on a literal
def twice (n : Nat) : Nat := 2 * n
example : twice 3 = 6 := rfl
```

Conversely, `rfl` *fails* when no chain of reductions connects the two sides -- typically when a variable blocks computation. `Nat`'s addition is defined by recursion on its *second* argument, so `n + 0` fires the ι rule and reduces to `n`, whereas `0 + n` is *stuck*: with `n` a bare variable there is no constructor for the recursor to fire on.

```lean
-- `n + 0` reduces to `n`, so this is `rfl`:
example (n : Nat) : n + 0 = n := rfl

-- `0 + n` is stuck (nothing to recurse on), so `rfl`
-- fails and you need `simp` or induction instead:
example (n : Nat) : 0 + n = n := by simp
```

Recognizing when a goal is "true by reduction" -- and therefore closed by `rfl` -- is one of the most useful instincts to develop; it is exactly the situation later chapters rely on whenever they say a step holds "by definition" or "definitionally".

# The universe hierarchy
%%%
tag := "type-universes"
%%%

Every term has a type; but a type is itself a term of some type. To keep the system consistent, these type-of-a-type (also called universes) are organized into a countably infinite hierarchy.

At the bottom sit the two universes you meet first (Here, the `#check` command gives the type of a term):

```lean
#check (42 : ℕ)         -- a term ...
#check (ℕ : Type)       -- ... whose type ℕ lives in `Type`
#check ((2 = 2) : Prop) -- a proposition ...
#check (Prop : Type)    -- ... and `Prop` itself lives in `Type`
```

`Type` (which is the same as `Type 0`) is the universe of ordinary data types (`ℕ`, `ℝ`, `Bool`, `List α`, ...), and `Prop` (which is the universe of *propositions*, i.e. True/False-statements). But `Type` cannot contain itself -- that would be paradoxical -- so `Type` in turn lives in a larger universe `Type 1`, which lives in `Type 2`, and so on without end:

```lean
#check (Type : Type 1)      -- Type   : Type 1
#check (Type 1 : Type 2)    -- Type 1 : Type 2
```

:::example "The connection of `Type` to `Sort`"

The whole tower is captured by a single keyword `Sort`:

* `Sort 0` is `Prop`;
* `Sort 1` is `Type 0`, i.e. `Type`;
* `Sort (u+1)` is `Type u`.

```lean
example : Sort 0 = Prop := rfl
example : Sort 1 = Type := rfl
example : Type = Type 0 := rfl
```

So `Sort` is the umbrella that unifies `Prop` and all the `Type u`, and the one rule governing the hierarchy is `Sort u : Sort (u+1)`. There is deliberately no `Type : Type`; *why* this restriction is needed -- it blocks a type-theoretic version of Russell's paradox -- is taken up in the {ref "universe-hierarchy"}[Mathematics part].
:::

*Why `Prop` is special.*
Of particular interest is the type `Prop`, which consists of statements that can be `True` or `False`. It includes mathematical statements, so either the hypotheses, or the goal of what is to be proven. A hypothesis in Lean has the form `hP : P`, which means `P` is true, and this statement is called `hP`. Synonomously, it means that `P` is true and `hP` is a proof of `P`. The hypotheses here have names `P Q R S`, and the proofs of the hypotheses `hP hQ hR hS`. All names can be arbitrary. Furthermore, there are hypotheses of the form `P → Q`, which is the statement that `P` implies `Q`. (Note the similarity to function notation as in `f : ℝ → ℝ`.)

We note three specifics which only apply to `Prop`:

*Proof irrelevance*: Note that `Prop` only records *that* a statement holds, but not *which* proof we chose. This is *proof irrelevance*, which means the following goal closes by `rfl`:

```lean
example (P : Prop) (h₁ h₂ : P) : h₁ = h₂ := rfl
```

For data living in a `Type` there is no such collapse, for obvious reasons. (The red squiggly line indicates an error, i.e. a proof which does not work.)

```lean +error
example (a b : ℕ) : a = b := rfl
```
See also {ref "prop-vs-type"}[Prop vs Type].

*`Prop` is impredicative*: As long as the body of a `∀` statement is a proposition, the whole `∀` is a `Prop` -- even when we range over an arbitrarily large universe of types:

```lean
-- Prop-valued body: stays `Prop`, however big the domain.
#check (∀ α : Type, α = α)     -- Prop
#check (∀ α : Type 5, α = α)   -- Prop
```

No `Type u` behaves this way. Replace the proposition `α = α` by `α → α`, and the universe of the `∀` is forced to grow with the domain, exactly as predicativity demands:

```lean
-- Type-valued body: the universe grows with the domain.
#check (∀ α : Type, α → α)     -- Type 1
#check (∀ α : Type 5, α → α)   -- Type 6
```

So the two syntactically parallel statements `∀ α : Type 5, α = α` and `∀ α : Type 5, α → α` land in wildly different places -- `Prop` versus `Type 6` -- purely because the first has a `Prop` body and the second a `Type` body. This asymmetry (a `∀` into `Prop` stays small; a `∀` into `Type u` must climb) is exactly what it means to say *`Prop` is impredicative and the `Type u` are predicative*.

(A definition can be made to work at *any* universe level at once; that uses `def`, so we defer it to the {ref "polymorphic-functions"}[chapter on functions].)

*Restricted (subsingleton) elimination*: A word on *elimination* first. A type's constructors *introduce* its values -- they build them (`Or.inl`, `isTrue`, `Nat.succ`, …). To *eliminate* a value is the opposite: to *use* it, by case analysis on which constructor produced it. That is what `match` does, and ultimately the job of the type's {ref "inductive"}[recursor]. *Eliminating into a type `T`* then means that this case analysis yields a result of type `T`. The restriction on `Prop` is about exactly this: a proof carries no observable content, so Lean forbids *reading data off a proof* by such case analysis -- otherwise a value could depend on *which* proof we had, which proof irrelevance declares meaningless. Eliminating a proposition may therefore, in general, only produce further propositions, not data. Deciding as a `Bool` which side of a disjunction holds is rejected:

```lean +error
example (a b : Prop) (h : a ∨ b) : Bool :=
  match h with
  | Or.inl _ => true
  | Or.inr _ => false
```

The error is telling: `recursor 'Or.casesOn' can only eliminate into 'Prop'`. The one exception is *subsingleton elimination*: a proposition with *at most one constructor*, all of whose fields are *themselves proofs*, provably has at most one inhabitant -- so eliminating it can reveal nothing, and Lean does allow it into *any* type. This covers `False` (no constructors, which is exactly why `False.elim` closes *any* goal), `Eq` (which is why we may `rw` even inside data-carrying goals), and `And` (both fields are proofs); but not `Or` (two constructors) nor `∃` (its first field is a genuine witness, not a proof). None of this restriction applies to `Type`: an inductive type in `Type` always eliminates into anything.

Why must it be this way? It is not bureaucracy -- consistency forces it, and for `Or` the argument is a little gem. What cannot escape here is not a *witness* (as it would be for `∃`) but the *tag*: the information *which* of the two branches holds. Take a true `a` and look at the proposition `a ∨ a`. Its two opposite injections are definitionally equal, by proof irrelevance:

```lean
example {a : Prop} (h : a) :
    (Or.inl h : a ∨ a) = Or.inr h := rfl
```

"Left or right?" is simply not a well-posed question about a proof of `a ∨ a` -- the tag does not exist as distinguishable content. So had the rejected `(a ∨ b) → Bool` above been allowed, then with `b := a` it would give `which (Or.inl h) = true` and `which (Or.inr h) = false`; but `Or.inl h ≡ Or.inr h`, so `true ≡ false` -- a contradiction. The indistinguishability of proofs forces the tag to stay trapped, exactly as it would have forced `3 ≡ 5` for a leaked `∃`-witness.

The escape mirrors the one for `∃`, one level up. The data-carrying counterpart of `a ∨ ¬a` is `Decidable a`, which -- crucially -- lives in `Type`, not `Prop`:

```
inductive Decidable (p : Prop) : Type where
  | isFalse (h : ¬p)
  | isTrue  (h :  p)
```

Because `Decidable p` is in `Type`, it *may* eliminate into `Type` -- which is exactly why `if h : p then _ else _` and `decide` compute. The two stories line up exactly:

:::table (align := left) +header
* + Proposition (in `Prop`)
  + Data version (in `Type`)
  + what stays hidden
* + `∃ x, q x`
  + `Σ x, q x`
  + the *witness*
* + `a ∨ ¬a`
  + `Decidable a`
  + the *tag* (which side)
:::

And the classical route mirrors `Classical.choose` precisely: `Classical.em : a ∨ ¬a` is always available (a `Prop`), but its data-carrying counterpart `Classical.propDecidable : Decidable a` goes through `Classical.choice` and is therefore `noncomputable`. The two halves -- `∃`/`Σ`/`choose` about the *witness*, `∨`/`Decidable`/`em` about the *tag* -- are one and the same story: computationally relevant information can leave the `Prop` world only if you place it in `Type` from the start, or pay for it noncomputably with the axiom of choice. (The `Nonempty`/`Classical.choice` version of this is taken up in the {ref "curry-howard"}[chapter on propositions and proofs].)

## How the universe of a type is determined
%%%
tag := "universe-determined"
%%%

You rarely write universe levels by hand -- Lean computes the universe of a compound type from the universes of its parts. A function type `α → β` lands in the *larger* of the two universes involved:

```lean
#check (ℕ → ℕ)        -- Type
#check (ℕ → Type)     -- Type 1  (because `Type : Type 1`)
```

# Inductive types
%%%
tag := "inductive"
%%%

Many everyday types in Lean -- `Nat`, `List`, `Option`, `Bool`, even `Empty` -- are *inductive* types. We have already dissected one of them, `Nat`, in the {ref "types-intro"}[introduction]: its two constructors `Nat.zero`/`Nat.succ`, and its recursor `Nat.rec`. This section is about the general mechanism -- how you *declare* such a type yourself, and which declarations Lean accepts.

You declare an inductive type by giving a name, the type's universe, and a list of *constructors*, each saying how to build a new element out of existing pieces. Declaring the natural numbers by hand reproduces exactly the structure of `Nat`:

```lean
inductive MyNat where
  | zero : MyNat
  | succ (n : MyNat) : MyNat
```

As with `Nat`, this single declaration introduces three things at once: the type `MyNat`; its two constructors `MyNat.zero` and `MyNat.succ`, so every element is either `zero` or `succ n`; and a *recursor* `MyNat.rec` -- the type's *eliminator*, the counterpart of its constructors -- of the same shape as `Nat.rec`, into which pattern matching, `cases`, and `induction` all translate. Its {ref "reduction-rules"}[iota rule], `MyNat.rec z s (.succ n) ⟶ s n (MyNat.rec z s n)`, is the firing we watched for `Nat`. And a recursor is not special to `inductive`: since a `structure` is a single-constructor inductive, it too has one -- `Point.rec` (from the next section) takes a single case, a function of the fields, and the projections `Point.x`, `Point.y` are defined through it.

The declaration only *forms the type*. How to actually build its elements and *define functions* on it -- typically by pattern matching on the constructors -- is the subject of {ref "terms"}[the next chapter], on constructing terms.

Proofs about an inductive type use the `induction` tactic, which applies the recursor for you: one subgoal per constructor, with an induction hypothesis for each recursive argument.

Inductive types also cover non-recursive data:

```lean
inductive Colour where
  | red | green | blue
```

and parameterized types:

```lean
-- `MyOption α` is either `none` or `some a` for some `a : α`.
inductive MyOption (α : Type) where
  | none : MyOption α
  | some (a : α) : MyOption α
```

Inductive types are the main mechanism by which new data types enter Lean; `Mathlib` uses them extensively, and understanding them is essential for reading the library. This also answers the question of the previous section from the other side: the universe of an inductive type must be large enough to hold all of its constructor arguments.

Not every `inductive` declaration is accepted, though. A constructor may mention the type being defined, but only *positively* -- never to the *left* of an arrow inside one of its arguments. This *strict positivity* condition keeps inductive types built from well-founded data and free of paradox. A tree branching over `ℕ` is fine, because `MyTree` occurs only to the *right* of `→`:

```lean
inductive MyTree where
  | node : (ℕ → MyTree) → MyTree   -- accepted: `MyTree` is positive
```

But a constructor that stores a *function out of* the type is rejected:

```
inductive Bad where
  | mk : (Bad → False) → Bad
-- error: (kernel) arg #1 of 'Bad.mk' has a non positive
--        occurrence of the datatypes being declared
```

The rejection is not pedantry: were `Bad` allowed, one could prove `False`. Project the stored function out of a `b : Bad` and apply it to `b` itself,

```
def app : Bad → (Bad → False) | .mk f => f
def neg (b : Bad) : False := app b b
```

so `neg : Bad → False`. Then `Bad.mk neg : Bad`, and `neg (Bad.mk neg) : False` is a closed proof of `False` (it even loops, `neg (Bad.mk neg) ⟶ neg (Bad.mk neg)` -- the untyped Ω combinator smuggled into the theory). Strict positivity outlaws exactly the negative occurrence that ties this self-applying knot -- the same consistency concern that rules out `Type : Type`. (That positivity is also *sufficient* for consistency -- every strictly positive type is the least fixed point of a monotone functor, so the theory has a model -- is a deep metatheorem, not something Lean proves about itself.)

# Structures
%%%
tag := "structures"
%%%

While inductive types let us define types with multiple constructors, many mathematical objects are better described as a *collection of named fields*. For example, a point in the plane has an `x`-coordinate and a `y`-coordinate. In Lean, we use `structure` for this.

A `structure` is a special case of an inductive type with exactly one constructor and named fields. Here is a simple example:

```lean
structure Point where
  x : ℕ
  y : ℕ
```

This declares a new type `Point` whose elements are records with two `ℕ` fields. (Both must be given in order to define a `Point`, which is the only way we can make such a Point, i.e. it only has a single constructor.) Like every declaration, it produces more than the type alone: a constructor `Point.mk` and one projection per field. We can inspect their types without building any value yet:

```lean
#check (Point.mk : ℕ → ℕ → Point)
#check (Point.x : Point → ℕ)
#check (Point.y : Point → ℕ)
```

Fields may be given *default values* as part of the declaration:

```lean
structure MyConfig where
  width : ℕ := 80
  height : ℕ := 24
  title : String := "Untitled"
```

These defaults are used whenever a value is built without specifying every field.

One structure can *extend* another, inheriting all of its fields:

```lean
structure Point3D extends Point where
  z : ℕ
```

so a `Point3D` has fields `x`, `y` (from `Point`) and `z`. This is particularly important in Mathlib, where the algebraic hierarchy uses structure extension extensively: `CommRing` extends `Ring`, which extends `Semiring`, and so on.

Structures are natural for representing mathematical objects. A *Gaussian integer* (a complex number with integer parts) is a pair of `ℤ`s,

```lean
structure MyComplex where
  re : ℤ
  im : ℤ
```

and a structure may bundle *data together with a property* -- here a linear map, carrying both a function and a proof that it respects addition:

```lean
structure MyLinearMap (α β : Type) [Add α] [Add β] where
  toFun : α → β
  map_add : ∀ x y : α, toFun (x + y) = toFun x + toFun y
```

This pattern of bundling data with properties is fundamental to how Mathlib organizes mathematics.

How to *construct* values of these types, read their fields, and define operations on them is the subject of {ref "terms"}[the next chapter].

# Inductive types vs structures
%%%
tag := "inductive-vs-structure"
%%%

When should you use `inductive` and when `structure`?

* Use `structure` when your type has a single constructor with named fields. Examples: points, complex numbers, algebraic structures.
* Use `inductive` when your type has multiple constructors. Examples: natural numbers, lists, trees, `Option`, `Bool`.

A `structure` is syntactic sugar for an inductive type with one constructor. The definition

```
structure Point where
  x : ℕ
  y : ℕ
```

is essentially equivalent to

```
inductive Point where
  | mk : ℕ → ℕ → Point
```

but the `structure` version gives us named fields, {ref "structure-values"}[dot notation], the possibility for default values, and the `extends` mechanism. (A `class` is in turn a `structure` marked for use by instance search; we return to it in the {ref "typeclasses"}[Typeclass] chapter.)

# Quotient types
%%%
tag := "quotient-types"
%%%

Alongside universes, function types, and inductive types, Lean has one more basic way to *form* a type: the *quotient*. Given a type `α` and a relation `r : α → α → Prop`, the type `Quot r` glues together elements that `r` relates -- it is `α` "seen up to `r`". This is how the chapter's opening remark, that `ℝ` is Cauchy sequences up to an equivalence, becomes an actual construction; `ℤ`, `ℚ`, `Multiset α` (lists up to reordering), and `ZMod n` are quotients too.

Its entire interface is four constants:

```lean
#check @Quot.mk     -- (r : α → α → Prop) → α → Quot r
#check @Quot.sound  -- r a b → Quot.mk r a = Quot.mk r b
#check @Quot.lift   -- (f : α → β) → (∀ a b, r a b → f a = f b) → Quot r → β
#check @Quot.ind
```

- `Quot.mk r` sends each element to its class.
- `Quot.sound` is the crux: if `r a b`, then the two classes are *the same term*. It is one of Lean's few genuine axioms (`#print axioms Quot.sound` reports `[Quot.sound]`).
- `Quot.lift` defines a function *out of* the quotient -- but only once you *prove* it respects `r` (the `∀ a b, r a b → f a = f b` argument), which is exactly the mathematician's "check that this is well-defined". And it computes: `Quot.lift f h (Quot.mk r a)` reduces to `f a`.
- `Quot.ind` proves a property of every quotient element by checking it on the classes `Quot.mk r a`.

In practice one usually goes through `Quotient`, a thin wrapper of `Quot` over a bundled equivalence relation (a `Setoid`). The status of `Quot.sound` as an axiom is taken up again in the {ref "axiom-quot"}[axioms chapter].
