import VersoManual
import Manual.Meta
import Leancourse.Misc.Defs
import Mathlib

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open MyDef

set_option pp.rawOnError true

#doc (Manual) "Equality" =>
%%%
htmlSplit := .never
tag := "equality"
%%%

Due to the multitude of types in Lean, we have to be careful about equality. In Lean, there are three types of equality:

* Syntactic equality: If two terms are letter-for-letter equal, then they are syntactically equal. However, there are a few more situations in which two terms are syntactically equal. Namely, if one term is just an abbreviation for the other (for example, `x = y` is an abbreviation for ` Eq x y`, where `Eq` is a function which takes two terms of the same type, and assigns `True` if they are the same and `False` otherwise), then these both terms are syntactically equal. Also equal are terms in which globally quantified variables have different letters. For example, `∀ x, ∃ y, f x y` and `∀ y, ∃ x, f y x` are syntactically equal.

* Definitional equality: Some terms are equal by definition in Lean. For example, `x : ℕ`, `x + 0` is by definition identical to `x`. However, `0 + x` is not   definitionally identical to `x`. This is apparently only due to the     internal definition of addition of natural numbers in Lean.

* Propositional equality: If there is a proof of `x = y`, then `x` and `y` are said to be propositionally equal. Similarly, terms `P` and `Q` are said to be propositionally equal if you can prove `P ↔ Q`. Some Lean tactics only work up to syntactic equality (such as `rw`), others (most) work up to definitional equality (such as `apply`, `exact`,...) This means that the tactic automatically transforms terms if they are syntactically or definitional equality.

There is a special kind of equality to be observed with sets and functions. For example, two functions are exactly the same if they return the same value for all values in the domain. This behavior is called *extensionality* in the theory of programming languages. (If extensionality applies, then, for example, two sorting algorithms are the same if they always produce the same result).

# Reduction rules and what `rfl` can do
%%%
tag := "reduction-rules"
%%%

Definitional equality is not magic -- it is generated by a fixed list
of *reduction* rules that the kernel applies to compute terms.  The
words *beta*, *eta*, and the rest come from the *lambda calculus* of
Alonzo Church in the 1930s, where functions are written `fun x => e`
and each rewriting rule was labelled with a Greek letter.  A
*reduction* is one directed computation step, `term ⟶ simpler term`.
Lean's kernel uses six of them:

:::table +header
* + Rule
  + What it does
  + Example
* + *alpha*
  + rename a bound variable
  + `fun x => x` and `fun y => y` agree
* + *beta*
  + apply a function: substitute the argument
  + `(fun x => x + 1) 4 ⟶ 4 + 1`
* + *eta*
  + function extensionality
  + `fun x => f x ⟶ f`
* + *delta*
  + unfold a definition
  + `twice 3 ⟶ 2 * 3`
* + *iota*
  + run a recursor on a constructor
  + `Nat.rec z s (n+1) ⟶ s n (Nat.rec z s n)`
* + *zeta*
  + substitute a `let`-binding
  + `let x := 4; x + x ⟶ 4 + 4`
:::

*Definitional equality* -- Lean's notion of "the same by computation"
-- is exactly the equivalence generated by these reduction rules
(together with eta-conversion).  And that is *precisely* what `rfl`
checks: `rfl` proves `a = b` whenever `a` and `b` reduce to a common
form.  So `rfl` is far stronger than "syntactically identical":

```lean
-- beta, then arithmetic computes (delta + iota)
example : (fun x => x + 1) 4 = 5 := rfl
example : 2 + 2 = 4 := rfl
example : List.length [7, 8, 9] = 3 := rfl

-- eta: a function equals its eta-expansion
example (f : Nat → Nat) : (fun x => f x) = f := rfl

-- zeta: a `let` unfolds
example : (let x := 4; x + x) = 8 := rfl

-- delta + iota: a defined function on a literal
def twice (n : Nat) : Nat := 2 * n
example : twice 3 = 6 := rfl
```

Conversely, `rfl` *fails* when no chain of reductions connects the two
sides -- typically when a variable blocks computation.  The classic
illustration is the one from the start of this chapter: `Nat`'s
addition is defined by recursion on its *second* argument, so

```lean
-- `n + 0` reduces to `n`, so this is `rfl`:
example (n : Nat) : n + 0 = n := rfl

-- `0 + n` is stuck (nothing to recurse on), so `rfl`
-- fails and you need `simp` or induction instead:
example (n : Nat) : 0 + n = n := by simp
```

`n + 0` computes away because the `0` is a concrete constructor the
recursor can fire on; `0 + n` is stuck until `n` itself becomes a
constructor.  Recognizing when a goal is "true by reduction" -- and
therefore closed by `rfl` -- is one of the most useful instincts to
develop.

(The kernel additionally treats all proofs of a `Prop` as equal --
*proof irrelevance* -- and computes on quotients; those foundational
points, and the axioms behind them, are taken up in the *Mathematics*
part.)
