import VersoManual
import Manual.Meta
import Leancourse.Misc.Defs
import Mathlib

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open MyDef

set_option pp.rawOnError true
set_option verso.docstring.allowMissing true

#doc (Manual) "Measure Theory in Mathlib" =>
%%%
htmlSplit := .never
tag := "measure-theory"
%%%

Measure theory in Mathlib is a substantial part of the library, covering
sigma-algebras, measurable functions, measures, integration, and probability.
It builds on the filter framework for convergence theorems. This section
gives an overview of the main definitions and how to work with them.

# Notation and naming conventions
%%%
tag := "measure-notation"
%%%

Several measure-theory symbols are unicode characters.  In VS Code,
hover over a symbol to see the backslash escape that types it.

:::table +header
* + Symbol
  + Lean name
  + Reads as
  + Typed as
* + `MeasurableSpace α`
  + `MeasurableSpace α`
  + "sigma-algebra on α"
  + (ASCII)
* + `MeasurableSet s`
  + `MeasurableSet s`
  + "s is measurable"
  + (ASCII)
* + `Measurable f`
  + `Measurable f`
  + "f is measurable"
  + (ASCII)
* + `Measure α`
  + `MeasureTheory.Measure α`
  + "measure on α"
  + (ASCII)
* + `volume`
  + `MeasureTheory.volume`
  + "the Lebesgue measure"
  + (ASCII)
* + `μ s`
  + `MeasureTheory.Measure.measureOf`
  + "measure of s under μ"
  + (ASCII)
* + `ℝ≥0`
  + `NNReal`
  + "nonnegative reals"
  + `\R\ge0`
* + `ℝ≥0∞`
  + `ENNReal`
  + "extended nonneg reals, 0 to ∞"
  + `\R\ge0\infty`
* + `∫ x, f x ∂μ`
  + `MeasureTheory.integral`
  + "Bochner integral of f w.r.t. μ"
  + `\int`, `\partial`
* + `∫⁻ x, f x ∂μ`
  + `MeasureTheory.lintegral`
  + "lower Lebesgue integral"
  + `\int\^-`
* + `∀ᵐ x ∂μ, p x`
  + `MeasureTheory.∀ᵐ`-notation
  + "p holds μ-almost-everywhere"
  + `\all\^m`
* + `f =ᵐ[μ] g`
  + `Filter.EventuallyEq`
  + "f equals g μ-almost-everywhere"
  + `=\^m[...]`
* + `μ.ae`
  + `MeasureTheory.Measure.ae`
  + "the almost-everywhere filter"
  + (ASCII)
:::

Naming hints.

- *Prefix `Is`* for properties of measures: `IsProbabilityMeasure μ`,
  `IsFiniteMeasure μ`, `IsSigmaFiniteMeasure μ`.
- *Prefix `ae`* (short for "almost everywhere"): `ae μ` is the filter
  of conull sets; `AEMeasurable f`, `AEStronglyMeasurable f`,
  `AEEqFun` are ae-variants of stronger regularity properties.
- The integral symbol `∫` takes a binder `∫ x, ...` followed by the
  measure `∂μ`.  Without `∂μ`, the integral is with respect to the
  default `volume` measure.
- `ℝ≥0∞` is the preferred codomain for measures: they take values in
  `[0, ∞]`.  Coercions to/from `ℝ` use `ENNReal.toReal`,
  `ENNReal.ofReal`.
- Almost-everywhere statements are just the filter quantifier `∀ᶠ`
  applied to the `ae` filter: `∀ᵐ x ∂μ, p x` is definitionally
  `∀ᶠ x in μ.ae, p x`.

# Sigma-algebras: MeasurableSpace
%%%
tag := "measurable-space"
%%%

A *sigma-algebra* (or *measurable space*) on a type `α` is specified by the
typeclass `MeasurableSpace α`. It tells Lean which subsets of `α` are
*measurable*.

{docstring MeasurableSpace}

```lean
-- ℝ has a measurable space structure (the Borel sigma-algebra)
#check (inferInstance : MeasurableSpace ℝ)

-- The whole space and the empty set are measurable
example : MeasurableSet (Set.univ : Set ℝ) :=
  MeasurableSet.univ

example : MeasurableSet (∅ : Set ℝ) :=
  MeasurableSet.empty

-- Complements of measurable sets are measurable
example (s : Set ℝ) (hs : MeasurableSet s) : MeasurableSet sᶜ :=
  hs.compl
```

Countable unions of measurable sets are measurable:

{docstring MeasurableSet.iUnion}

On `ℝ` (and other topological spaces), the default sigma-algebra is the
*Borel sigma-algebra*, generated by the open sets.

# Measurable functions
%%%
tag := "measurable-functions"
%%%

A function `f : α → β` between measurable spaces is *measurable* if the
preimage of every measurable set is measurable.

{docstring Measurable}

```lean
-- The identity function is measurable
example {α : Type*} [MeasurableSpace α] :
    Measurable (id : α → α) :=
  measurable_id

-- Composition of measurable functions is measurable
example {α β γ : Type*} [MeasurableSpace α] [MeasurableSpace β]
    [MeasurableSpace γ] (f : α → β) (g : β → γ)
    (hf : Measurable f) (hg : Measurable g) :
    Measurable (g ∘ f) :=
  hg.comp hf
```

Continuous functions are measurable (with Borel sigma-algebras):

{docstring Continuous.measurable}

Important: every continuous function is measurable (when both spaces carry
the Borel sigma-algebra), but not vice versa.

# Measures
%%%
tag := "measures"
%%%

A *measure* on a measurable space `α` is a countably additive function from
measurable sets to `[0, ∞]`. In Mathlib, measures take values in `ℝ≥0∞`
(the extended nonnegative reals, typed `\R\ge0\infty` or using `ENNReal`).

{docstring MeasureTheory.Measure}

```lean
-- A measure assigns a value in ℝ≥0∞ to each measurable set
example {α : Type*} [MeasurableSpace α]
    (μ : MeasureTheory.Measure α) (s : Set α) : ENNReal :=
  μ s

-- The measure of the empty set is 0
example {α : Type*} [MeasurableSpace α]
    (μ : MeasureTheory.Measure α) : μ ∅ = 0 :=
  MeasureTheory.measure_empty
```

Monotonicity: if `s ⊆ t`, then `μ s ≤ μ t`:

{docstring MeasureTheory.measure_mono}

# The Lebesgue measure on ℝ
%%%
tag := "lebesgue-measure"
%%%

The standard measure on `ℝ` is the *Lebesgue measure*, available as
`MeasureTheory.volume` (or via the notation `volume`).

The Lebesgue measure of an interval:

{docstring Real.volume_Icc}

```lean
-- volume is a measure on ℝ
open MeasureTheory in
#check (volume : Measure ℝ)
```

# A small worked computation
%%%
tag := "lebesgue-worked"
%%%

A concrete sanity check: the Lebesgue measure of the closed unit
interval is `1`.

```lean
open MeasureTheory in
example : volume (Set.Icc (0 : ℝ) 1) = 1 := by
  rw [Real.volume_Icc]
  simp
```

Mathlib also gives the volume of `Ico`, `Ioo`, `Ioc` (all equal to
`b - a` when `a ≤ b`); a half-open interval can be written as a
disjoint union with a single point, and points have measure zero
(`Real.volume_singleton`).

# Integration
%%%
tag := "integration"
%%%

Mathlib provides the Bochner integral `∫ x, f x ∂μ` (typed `\int`), which
generalizes both the Lebesgue integral for real-valued functions and the
integral for Banach-space-valued functions.

{docstring MeasureTheory.integral}

Linearity of the integral:

{docstring MeasureTheory.integral_add}

{docstring MeasureTheory.integral_smul}

Integral over an indicator function:

{docstring MeasureTheory.integral_indicator}

For nonnegative functions, there is also the `∫⁻` (lower Lebesgue integral)
taking values in `ℝ≥0∞`:

```lean
#check @MeasureTheory.lintegral
-- ∫⁻ x, f x ∂μ : ℝ≥0∞
```

# Convergence theorems
%%%
tag := "convergence-theorems"
%%%

The fundamental convergence theorems of measure theory are available in Mathlib:

*Monotone Convergence Theorem*: If `f₀ ≤ f₁ ≤ f₂ ≤ ...` is an increasing
sequence of nonnegative measurable functions, then
`∫⁻ x, (⨆ n, f n x) ∂μ = ⨆ n, ∫⁻ x, f n x ∂μ`.

{docstring MeasureTheory.lintegral_iSup}

*Dominated Convergence Theorem*: If `fₙ → f` pointwise a.e., and
`|fₙ| ≤ g` a.e. for an integrable `g`, then `∫ x, fₙ x ∂μ → ∫ x, f x ∂μ`.

{docstring MeasureTheory.tendsto_integral_of_dominated_convergence}

These theorems are stated using filters: convergence of the integrals is
expressed as `Filter.Tendsto` with respect to `Filter.atTop`.

# Probability measures
%%%
tag := "probability-measures"
%%%

A measure `μ` is a *probability measure* if `μ Set.univ = 1`. Mathlib uses
the typeclass `MeasureTheory.IsProbabilityMeasure μ` for this.

{docstring MeasureTheory.IsProbabilityMeasure}

```lean
-- If μ is a probability measure, then μ(s) ≤ 1 for all s
example {α : Type*} [MeasurableSpace α]
    (μ : MeasureTheory.Measure α)
    [MeasureTheory.IsProbabilityMeasure μ] (s : Set α) :
    μ s ≤ 1 := by
  calc μ s ≤ μ Set.univ :=
        MeasureTheory.measure_mono (Set.subset_univ s)
    _ = 1 :=
        MeasureTheory.IsProbabilityMeasure.measure_univ
```

There is also `MeasureTheory.IsFiniteMeasure μ` for finite measures and
`MeasureTheory.SigmaFinite μ` for sigma-finite measures.

# Almost everywhere and ae-filter
%%%
tag := "ae-filter"
%%%

Many statements in measure theory hold "almost everywhere" (a.e.), meaning
outside a set of measure zero. In Mathlib, this is captured by the
*ae-filter* `MeasureTheory.Measure.ae μ`, which is the filter of sets whose
complement has measure zero.

{docstring MeasureTheory.ae}

```lean
-- "f = g almost everywhere" means {x | f x ≠ g x} has measure zero
open MeasureTheory in
example {α : Type*} [MeasurableSpace α]
    (μ : Measure α) (f g : α → ℝ) :
    f =ᵐ[μ] g ↔ ∀ᶠ x in ae μ, f x = g x :=
  Iff.rfl
```

This is a beautiful example of the filter framework in action: "almost
everywhere" is just "eventually" with respect to the ae-filter.

# Conditional expectation
%%%
tag := "conditional-expectation"
%%%

For probability theory, Mathlib provides conditional expectation with respect
to a sub-sigma-algebra. This is an advanced topic, but the key definition is:

{docstring MeasureTheory.condExp}

The conditional expectation `μ[f | m]` (notation
`MeasureTheory.condExp m μ f`) is the unique (up to
`μ`-almost-everywhere equality) function `g : α → E` such that

- `g` is `m`-measurable, where `m` is a sub-sigma-algebra of the
  ambient sigma-algebra on `α`;
- for every `m`-measurable set `s`,
  `∫ x in s, f x ∂μ = ∫ x in s, g x ∂μ`.

In probability terms: `μ[f | m]` is the best `m`-measurable
predictor of `f` in the `L²` sense.  The defining property is
captured by `MeasureTheory.setIntegral_condExp`.  Mathlib has the
linearity, monotonicity, tower, and Jensen properties; the API
lives in the `MeasureTheory` namespace and uses `condExp_` as a
prefix.

The conditional expectation `μ[f | m]` is the unique (a.e.) `m`-measurable
function that agrees with `f` in integral over every `m`-measurable set.

# Summary of key Mathlib API for measure theory
%%%
tag := "measure-api-summary"
%%%

:::table +header
* + Concept
  + Mathlib name
* + Sigma-algebra
  + `MeasurableSpace α`
* + Measurable set
  + `MeasurableSet s`
* + Measurable function
  + `Measurable f`
* + Measure
  + `MeasureTheory.Measure α`
* + Lebesgue measure
  + `MeasureTheory.volume`
* + Bochner integral
  + `∫ x, f x ∂μ`
* + Lebesgue integral
  + `∫⁻ x, f x ∂μ`
* + Probability measure
  + `IsProbabilityMeasure μ`
* + Almost everywhere
  + `∀ᶠ x in μ.ae, p x`
* + Integrable
  + `MeasureTheory.Integrable f μ`
* + Conditional expectation
  + `MeasureTheory.condexp`
:::

Working with measure theory in Mathlib requires familiarity with `ℝ≥0∞`
(extended nonnegative reals) and the filter framework. Many lemmas require
measurability or integrability hypotheses, so expect to prove these as
side goals.
